### PR TITLE
refactor[response]:variable declarations + log descriptions

### PR DESCRIPTION
**Pull request by AdrianSkar**
- Change variable declarations to use `const` and `let`
- Add descriptions for what is logged in the console

### CODE REVIEW

**Comment by teoli2003** [comment]
Once #21 is merged, we should rebase this and merge it.

**Comment by schalkneethling** [comment]
Hey @AdrianSkar, welcome to the community! Thank you for your contribution. #21 has been merged and so if you could address the conflicts and merge in the latest from `master` we can get this one merged.

**Comment by AdrianSkar** [comment]
> Hey @AdrianSkar, welcome to the community! Thank you for your contribution. #21 has been merged and so if you could address the conflicts and merge in the latest from `master` we can get this one merged.

Hi there! I can't see the branch/conflicts here. I'm trying with my local setup and with GitHub's editor (same URL but .dev) but throws me this:
image

Shall I create a new one?

**Comment by teoli2003** [comment]
This is weird; as I'm not using GitHub's editor (that looks like a web version of VSCode), I can't help on this point.

But feel free to open a new PR if it is less hassle. We will deal with this PR in it and close this one.

Thanks again for your help!

**Comment by AdrianSkar** [comment]
Done at #28. Thank you!

**Pull request closed without merging**
